# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qheLnAeBtC0ZsJFGm6sNtrOmaCZOq-9U
"""

def jaccard_similarity(text1, text2):
    # Split texts into sets of words
    set1 = set(text1.split())
    set2 = set(text2.split())
    #The jaccard_similarity function now returns both the similarity score and the set of common words.
    #The intersection variable contains the words that appear in both texti and text2.
    # The common words set is printed alongside the similarity score.

    # Find intersection and union
    intersection = set1.intersection(set2)
    union = set1.union(set2)

    # Calculate Jaccard similarity
    similarity = len(intersection) / len(union)

    # Return similarity score and intersection (common words)
    return similarity, intersection

# Input texts
text1 = "This is a sample sample text about is this legal sample issues."
text2 = "This text legal discusses legal and ethical This issues in legal computing."

# Calculate similarity and get common words
similarity, common_words = jaccard_similarity(text1, text2)

# Print results
print(f"Similarity: {similarity:.2f}")
print(f"Common words: {common_words}")
