# -*- coding: utf-8 -*-
"""OUMAR 2409001122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199l6Bz0J-qTSEBxxxF4hX-We3KAFoE1K
"""

# Define phishing keywords
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]
#These are words commonly found in phishing emails.
#The script will check if an email contains any of these words.

# Load the dataset (uploaded file)
emails = pd.read_csv("/content/2409001122.csv.csv")

# Check if the 'content' column exists
if 'Content' in emails.columns:
    # Apply phishing detection
    emails["is_phishing"] = emails["Content"].apply(
        lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
    )


    # Save the processed file
    emails.to_csv("/content/analyzed_/content/2409001122.csv.csv", index=False)
    print("Phishing detection complete. ")
else:
    print("Error: The 'content' column is missing from the dataset.")