# -*- coding: utf-8 -*-
"""uok.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcj78JbBH0PYvgy0Xn1x9Sbi1WeT1TVY
"""

import requests


def check_website(url):
  try:
    response=requests.get(url,timeout=5)
    return f"{url} is up status : {response.status_code}"
  except requests.exceptions.RequestException:
    return f"{url} is unreachable."

print(check_website("https://uok.ac.rw/"))